// lib/skills-data.tsx
import { Shield, Code, Cpu, TrendingUp } from "lucide-react";

export const skillCategories = [
  {
    title: "Web3 & Blockchain",
    icon: <Shield className="w-6 h-6" />,
    skills: [
      "Solidity 0.8.20+",
      "Ethers.js",
      "Web3.js",
      "Wagmi",
      "RainbowKit",
      "Smart Contracts",
      "ERC-20/721/1155",
      "DeFi Protocols",
      "Account Abstraction",
      "ZeroDev SDK",
      "Hardhat",
      "OpenZeppelin",
      "Metamask",
      "WalletConnect",
      "Multichain Development",
      "Chainlink Oracles",
      "IPFS & Filecoin",
      "NFT Standards & Marketplaces",
    ],
  },
  {
    title: "Frontend Development",
    icon: <Code className="w-6 h-6" />,
    skills: [
      "React.js 18",
      "Next.js 15",
      "TypeScript",
      "Tailwind CSS 4",
      "shadcn/ui",
      "Material-UI",
      "Vite 5",
      "JavaScript ES6+",
      "React Query/TanStack Query",
      "Framer Motion",
      "React Hook Form",
      "Storybook",
      "Vitest",
    ],
  },
  {
    title: "AI & Automation",
    icon: <Cpu className="w-6 h-6" />,
    skills: [
      "Prompt Engineering",
      "Claude Sonnet",
      "Claude Opus",
      "GPT-4o",
      "GPT-4o mini",
      "o1-preview",
      "o1-mini",
      "DeepSeek-V3",
      "Grok-3",
      "Gemini 2.0 Flash",
      "Development Acceleration",
      "AI-assisted Coding",
      "Cursor IDE",
      "GitHub Copilot",
    ],
  },
  {
    title: "Backend & Database",
    icon: <TrendingUp className="w-6 h-6" />,
    skills: [
      "Node.js",
      "Express",
      "PHP 8",
      "MongoDB",
      "MariaDB",
      "MySQL",
      "REST APIs",
    ],
  },
];
