// lib/skills-data.tsx
import { Shield, Code, Cpu, TrendingUp } from "lucide-react";

export const skillCategories = [
  {
    titleKey: "web3Blockchain",
    title: "Web3 & Blockchain",
    icon: <Shield className="w-6 h-6" />,
    skills: [
      "Solidity 0.8.20+",
      "Ethers.js",
      "Web3.js",
      "Wagmi",
      "RainbowKit",
      "Smart Contracts",
      "ERC-20/721/1155",
      "DeFi Protocols",
      "Account Abstraction",
      "ZeroDev SDK",
      "Hardhat",
      "OpenZeppelin",
      "Metamask",
      "WalletConnect",
      "Multichain Development",
      "Chainlink Oracles",
      "IPFS & Filecoin",
      "NFT Standards & Marketplaces",
    ],
  },
  {
    titleKey: "frontendDev",
    title: "Frontend Development",
    icon: <Code className="w-6 h-6" />,
    skills: [
      "React.js 18/19",
      "Next.js 15/16",
      "TypeScript",
      "Tailwind CSS 4",
      "shadcn/ui",
      "Material-UI",
      "Vite 5",
      "JavaScript ES6+",
      "React Query/TanStack Query",
      "Framer Motion",
      "React Hook Form",
      "Zustand",
      "Recharts D3",
      "Zod",
      "date-fns",
      "PWA",
      "Canvas API",
      "i18n/i18next",
      "Vitest",
    ],
  },
  {
    titleKey: "aiAutomation",
    title: "AI & Automation",
    icon: <Cpu className="w-6 h-6" />,
    skills: [
      "Prompt Engineering",
      "Claude 4 Sonnet",
      "Claude Opus 4.6",
      "GPT-4.1",
      "GPT-4.1 mini",
      "o3",
      "o4-mini",
      "DeepSeek-V3",
      "Grok-3",
      "Gemini 3",
      "Gemini 3 Flash",
      "Google Antigravity",
      "Development Acceleration",
      "AI-assisted Coding",
      "Cursor IDE",
      "GitHub Copilot",
    ],
  },
  {
    titleKey: "backendDb",
    title: "Backend & Database",
    icon: <TrendingUp className="w-6 h-6" />,
    skills: [
      "Node.js",
      "Express",
      "FastAPI",
      "Python",
      "Prisma",
      "Supabase",
      "PostgreSQL",
      "MongoDB",
      "MariaDB",
      "MySQL",
      "REST APIs",
      "WebSocket",
      "AWS (S3, CloudFront, SES)",
      "Terraform",
      "GitHub Actions",
      "Docker",
    ],
  },
];
